### ISSUE TITLE
Problems with errors 

### ISSUE THREAD

**Issue by Artessan** [themsaid/laravel-mail-preview#12]
Hey i am try to use the package but when i abort to personalize the errors page i get this error. 
![captura de pantalla 22](https://cloud.githubusercontent.com/assets/4217243/14893309/a05e9ed0-0d38-11e6-9cdf-db8042987d42.png)

**Comment by themsaid** [comment]
Can you explain what are you trying to do?

**Comment by Artessan** [comment]
I'm trying to custom  the error page of my app and when I do a error or make artisan down i have this error.

**Comment by jaumeavila** [comment]
It happens to me exactly the same, without doing anything.
If you go to MailPreviewMiddleware.php in line 24 it calls
$response = $this->handleException($request, $e);
but this method does not exist.

**Comment by sebastiandedeyne** [comment]
Just came across the same issue, the `handleException` method doesn't exist in the middleware.

Is there a reason why there's a try/catch for the response? Can't the middleware just leave the errors to the application?

**Comment by jaumeavila** [comment]
I agree with Sebastian. What I have done is to comment the code regarding the call of handleException.

**Comment by themsaid** [comment]
I'm fixing it now and will tag a new version. Thanks for reporting :)

**Comment by themsaid** [comment]
That should be fixed now, exception shall be handled normally via the application.

**Comment by sebastiandedeyne** [comment]
That was fast, thanks!

**Comment by themsaid** [comment]
welcome :) check it out and let me know if there's still an issue.

**Comment by jaumeavila** [comment]
Thanks!

**Comment by themsaid** [comment]
Most welcome @jaumeavila
