### ISSUE TITLE
laravel 5.1

### ISSUE THREAD

**Issue by sixty8** [themsaid/laravel-mail-preview#14]
Driver [preview] not supported.

**Comment by mgufrone** [comment]
+1 I got the same error

**Comment by themsaid** [comment]
Can you please confirm it was fixed in v1.2.4 ?

**Comment by mgufrone** [comment]
it doesn't show exception any more, but it doesn't generate any files inside the specified output directory. (my output directory is storage/email-previews as this package suggested)

**Comment by Braunson** [comment]
I'm receiving this in 5.4, using ^1.2 ...

**Comment by themsaid** [comment]
@braunson I don't seem to be able to replicate, can you please double check the installation instruction?

**Comment by Braunson** [comment]
@themsaid Sorry, figured it out, had to `composer-dumpautoload` and it was caused by an error from another package. Working on 5 .4 :)
