### ISSUE TITLE
Laravel 5.4: Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by wyandotte** [themsaid/laravel-mail-preview#21]
Installed this package today on a Laravel 5.4 installation. However, when I try to use it, it throws an error, `Call to undefined method Illuminate\Foundation\Application::share()`. 

Indeed, from the Laravel 5.4 upgrade guide:

> `share` Method Removed

> The `share` method has been removed from the container. This was a legacy method that has not been documented in several years. If you are using this method, you should begin using the `singleton` method instead

`share` is used in the [MailProvider](
https://github.com/themsaid/laravel-mail-preview/blob/master/src/MailProvider.php#L33). However, changing it directly to `singleton` without changing anything else also doesn't work: `Container.php line 988: Illegal offset type in unset`.

**Comment by themsaid** [comment]
Thank you, that was fixed :)
