### ISSUE TITLE
L5.4 supported yet?

### ISSUE THREAD

**Issue by Bulmer** [themsaid/laravel-mail-preview#22]
Just wondering if this has full L5.4 support yet? I've installed it in my L5.4 project and although there are no apparent errors, its not creating the html files.

**Comment by breadlesscode** [comment]
Im using Laravel 5.4 and everything works fine ;)
Did you set ```MAIL_DRIVER=preview```?
Did you add the ServiceProvider to app config?

**Comment by KoziaikinDmitriy** [comment]
Hello, when I using this package, I set MAIL_DRIVER=preview, add ServiceProvider to app config. E-mail saved in my folder, but not sending to user.

**Comment by breadlesscode** [comment]
I think this package is for testing emails without sending them ;)
