### ISSUE TITLE
Permanently keep the preview link box up

### ISSUE THREAD

**Issue by sebastiandedeyne** [themsaid/laravel-mail-preview#24]
Sometimes I miss the preview box because I've tabbed away to something else. Is the timeout on the preview link necessary? Or could we make it configurable? I'd prefer to have it up there permanently.

I'm Willing to send a PR if you decide on something!

**Comment by coderabbi** [comment]
👍 for configurable delay.

**Comment by themsaid** [comment]
I'm almost sure you forgot about this issue @sebastiandedeyne, sorry for not getting back to you earlier :)

But please feel free to submit the PR if you're still interested.
