### ISSUE TITLE
Route caching

### ISSUE THREAD

**Issue by fridzema** [themsaid/laravel-mail-preview#26]
Hello Themsaid,

First of all big thumbs up for your package, really like it!
I am used to cache my routes in production, but with your package its currently not possible to do.

[LogicException]                                                                  
Unable to prepare route [themsaid/mail-preview] for serialization. Uses Closure.

Do you have a fix for this or any plans to change this in the future?

**Comment by coderabbi** [comment]
I, too, eschew closures in routes for this reasons, but pending a possible update (or not), I'd suggest conditionally adding the service provider a la https://mattstauffer.co/blog/conditionally-loading-service-providers-in-laravel-5.

**Comment by themsaid** [comment]
Fixed now :)
