### ISSUE TITLE
Prob with Laravel 5.1

### ISSUE THREAD

**Issue by atefBB** [themsaid/laravel-mail-preview#3]
Hey, Mohamed, I have used this package this may laravel 5.1 app but it generate an error when I typed: composer require ... any ideas?

**Comment by themsaid** [comment]
Can you share the error?

**Comment by atefBB** [comment]
![fff](https://cloud.githubusercontent.com/assets/10966925/13934421/6cbf3f4c-efb2-11e5-8c9f-c1a617b3ad4a.png)

**Comment by themsaid** [comment]
I just updated the package dependencies to work for laravel 5.1.

Please run the composer command and update me:

```
composer require themsaid/laravel-mail-preview
```

**Comment by atefBB** [comment]
Thanks, I'll try it.
