### ISSUE TITLE
Open directly in the browser?

### ISSUE THREAD

**Issue by franzliedke** [themsaid/laravel-mail-preview#4]
How about opening the HTML files that are sent directly in the default browser?

I believe the [letter_opener gem](https://github.com/ryanb/letter_opener) for Rails does this - would be very handy.

**Comment by themsaid** [comment]
I wonder if that's a good idea, what if the code sends multiple emails after a specific action?

However the concept itself is interesting, Is it possible to open a web browser via CLI? What if I'm using Vagrant or so, how do I detect the host's default browser?

**Comment by franzliedke** [comment]
It would need to be an optional feature...

> Is it possible to open a web browser via CLI?
It must be, that's why I referenced the letter_opener gem.

Not sure about Vagrant, that is probably not possible.

**Comment by themsaid** [comment]
It's mentioned that a library called launchy is used: https://github.com/copiousfreetime/launchy.

There are some examples out there on how to launch the default web browser, but every platform has a different command (`xdg-open` for Linux, `start` for Windows, and `open` for OSX). So yeah detecting the OS and firing the right command might does the job.

Maybe I'll look into implementing this sometime later. If you can help I'd really appreciate that.
