### ISSUE TITLE
Embedded image not showing up

### ISSUE THREAD

**Issue by uyab** [themsaid/laravel-mail-preview#5]
I use `$message->embed(path/to/file.jpg)` to display embedded image, and the HTML generated was something like this: `cid:948ff85080e6ad80f6e3d8bac0a6fd14@swift.generated`, and of course it is something that not recognized by browser.

**Comment by themsaid** [comment]
For this you may use the generated `.eml` file to preview your message instead. There's no known method to retrieve the path to the original file from the Swift_Image type.

The `.eml` file will give you realistic preview in any email client, so it might be better to have accurate results.
