### ISSUE TITLE
Error when To header is empty

### ISSUE THREAD

**Issue by motia** [themsaid/laravel-mail-preview#54]
Hi, I am sending an email with only "BCC", then an error occurs as the "To" header is empty.
The error happens when the preview file name is generated. Here is [the line causing it](https://github.com/themsaid/laravel-mail-preview/blob/c4b5a0551c20f8f53c4cb33b7629478e5aad85ee/src/PreviewTransport.php#L83)

A possible solution would be to use the "CC" and "BCC" to generate the filename.
```
        $to = '';
        foreach ([$message->getTo(), $message->getCc(), $message->getBcc()] as $receipents) {
            if (!empty($receipents)) {
                $to = str_replace(['@', '.'], ['_at_', '_'], array_keys($receipents)[0]);
                break;
            }
        }
```
I will be happy to make PR. Let me know if you have better idea.

Thanks.

**Comment by themsaid** [comment]
Fixed that in 3.1.0
