### ISSUE TITLE
Is it possible to send emails AND save a HTML version?

### ISSUE THREAD

**Issue by JayBizzle** [themsaid/laravel-mail-preview#7]
We would like to actually send emails AND save a HTML version for our records.

Is this possible with this library?

Thanks

**Comment by themsaid** [comment]
Currently not, the package acts as your only mail driver so it stops sending emails and saves them on disk instead, but it's quite useful to include such a feature, I'll give it a shot soon and get back to you with the results.

I'll be releasing a new version of the package during the next few days, hopefully that'll be included.

**Comment by JayBizzle** [comment]
:+1:

**Comment by themsaid** [comment]
Giving it a second thought, can you please share a use case where you want the mail to be sent but also save it on disk?

**Comment by JayBizzle** [comment]
Hmmm, thinking about it, I could just render and return the email view and store it to the file system as well as sending pretty easily without any kind of package.

So, perhaps I was just being a little lazy hoping this package could do it for me 🤓

**Comment by themsaid** [comment]
Aren't we all looking for a super hero package that does everything for us? 😀

**Comment by sebastiaanluca** [comment]
@themsaid For an upcoming project, a client wants to send e-mails but also save a preview of that sent e-mail to review later (or by other admins) :)

**Comment by themsaid** [comment]
well, I'd absolutely accept a PR for that :)

The thing is this package replaces the mail driver configs completely, I think the best option here is to listen to a mail sent event, let the package save the email to disk, but send the actual email from the event listener.
